# Generated by Django 2.1 on 2019-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0002_remove_medicine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
