# Generated by Django 2.1 on 2019-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0003_auto_20190418_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
