# Generated by Django 2.1 on 2019-04-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0004_auto_20190418_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
