# Generated by Django 2.1 on 2019-04-18 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0005_auto_20190418_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='pincode',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(9999999999)),
        ),
    ]
