# Generated by Django 2.1 on 2019-04-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0006_auto_20190418_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
