# Generated by Django 2.1 on 2019-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0008_auto_20190419_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='drug',
            field=models.CharField(max_length=100),
        ),
    ]
