# Generated by Django 2.1 on 2019-04-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0009_auto_20190419_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
