# Generated by Django 2.1 on 2019-04-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0011_auto_20190419_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='description',
            new_name='name',
        ),
    ]
